// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxS6KqKGWP2O-SmY4FMw7YlsKyT--SASw',
    appId: '1:1016977356542:android:d19a35d44ecc92570b17af',
    messagingSenderId: '1016977356542',
    projectId: 'exam-terms',
    storageBucket: 'exam-terms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2rHlkv0Nnk0Yl7FfuBYp5MA6ZZz9P4WQ',
    appId: '1:1016977356542:ios:6ec6bd9933059e270b17af',
    messagingSenderId: '1016977356542',
    projectId: 'exam-terms',
    storageBucket: 'exam-terms.appspot.com',
    iosBundleId: 'com.example.lab3',
  );

}
